// Importing redirects from CSV output
// generated by: npm run build-redirects
const redirects = require('./server/build-redirects/output')

const nextConfig = {
  async redirects() {
    return redirects
  },
};

// const nextConfig = {
//   async redirects() {
//     return [
//       {
//         source: '/cromwell',
//         destination:
//           'https://www.cromwell.co.uk',
//         permanent: true,
//       },
//       {
//         source: '/portfolio',
//         destination: 'https://rolandlevy.co.uk',
//         permanent: true,
//       },
//       {
//         source: '/next',
//         destination: 'https://nextjs.org',
//         permanent: true,
//       },
//     ];
//   },
// };

module.exports = nextConfig